# Generated by Django 4.2.4 on 2023-08-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='work_space_id',
            new_name='workspace',
        ),
    ]
