# Generated by Django 4.2.4 on 2023-08-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0002_rename_work_space_id_task_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
