# Generated by Django 4.2.4 on 2023-08-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_space', '0003_workspace_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
